name: logistic_app
version: 0.0.1
description: Logistic App - Ingenieria de Software II - 2016-II
author: Jorge Neyra <hjneyra@ucsp.edu.pe>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  di: ">=3.3.4 <4.0.0"
  crypto: ">=0.9.0 <0.10.0"
  postgresql: any
  rpc: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
